---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r}
library(ggplot2) 
h <- sqrt(mobiles$px_height)
w <- mobiles$px_width
```

```{r}
plot(h~w, data=mobiles, pch = 20, col="red")
```

```{r}
model <- lm(formula = h ~ w)
model
```

```{r}
summary(model)

```

```{r}
ggplot(mobiles, aes(h, w)) +
  geom_point() +
  stat_smooth(method = lm, se = F)
```

```{r}
plot(h, predict(model), xlab="Прогнозовані моделлю значення", "ylab" = " Значення спостережень", col="red", pch=20)
abline(c(0, 1), col="black", lwd=3)
```

```{r}
plot(predict(model), residuals(model), col="red", pch=20)
abline(0, 0, col="black", lwd=3)
```

```{r}
plot(c(1:length(h)), resid(model), xlab = "Порядковий номер", ylab = "Значення залишків", main = "Значення залишків за порядковим номером")
abline(h = 0)
```

```{r}
qqnorm(residuals(model), col="turquoise", pch=20)
qqline(residuals(model), col="lightseagreen", lwd=3)
```

```{r}
shapiro.test(residuals(model))
```

```{r}
bptest(model)
```
```{r}
gvlma(model)

```